### ISSUE TITLE
Where we need help / To-Do List

### ISSUE THREAD

**Issue by bytebone** [justrainer/selfhost-guides#2]
# Core documentation that requires extension
- [ ] the firewall guide at [/main/src/hardening/firewall.md](/justrainer/how2host/blob/main/src/hardening/firewall.md)
- [ ] setup guides for more reverse proxies
  - [ ] Caddy
  - [ ] Plain Nginx
  - [ ] Traefik
  - [ ] Cloudflare Tunnels
- [ ] new guide in "First Steps" for Docker networking (includes refactoring of other guides)
- [ ] adding screenshots & images to all the guides - **especially the first steps**
- [ ] rewriting app guides and first steps to be proxy-agnostic

# App Guides

|| App | Status |
|-|-|-|
|✅| AdGuard Home | completed in #6 |
|✅| Vaultwarden | completed |
|| PiHole with LXC | author needed |
|| Full Media Stack | author needed |
|📝| Baserow | claimed by @justrainer |
|| Immich | author needed |
|| Nextcloud | author needed |

If you have additional ideas for a guide that would fit the project, feel free to comment it in this thread.

# Other, minor bits and pieces
- [ ] design a logo / favicon
- [ ] thoughts about SEO
